name: CI Pipeline

# Trigger the workflow on push to any branch and on pull request to the main branch
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version (you can change this to the version you're using)

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests (if any)
      run: |
        npm test  # This assumes you have a test script defined in package.json
        # If you don't have tests, you can skip this step or modify it

    - name: Build the application (optional)
      run: |
        npm run build  # Run build if you have a build script in package.json (optional)

    - name: Check for Dockerfile (optional)
      run: |
        if test -f "Dockerfile"; then echo "Dockerfile exists"; else echo "No Dockerfile found"; fi

    - name: Build Docker image (optional)
      run: |
        docker build -t ecommerce-app .
        docker images

    - name: Run application (optional, only for verification)
      run: |
        docker run -d -p 3000:3000 ecommerce-app
        curl http://localhost:3000  # Test if the server responds
